myapp/config/routes.rb
Rails.application.routes.draw do
  resources :folders do
    get 'add_urls', to: 'folders#add_urls'
    post 'add_urls', to: 'folders#add_urls'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp/app/models/folder.rb
class Folder < ApplicationRecord
  has_many :urls, dependent: :destroy
end

myapp/app/models/url.rb
require 'net/http'
require 'uri'

class Url < ApplicationRecord
  belongs_to :folder
  validates :url,
    length: { minimum: 11 },
    format: /\A#{URI::regexp(%w(http https))}\z/

  def acquire_title
    html = Net::HTTP.get(URI.parse(self.url))    
    html = html.force_encoding('UTF-8')
    html = html.gsub(/\R/, '')
    m = html.match(/<title>(.*)<\/title>/)
    if m
      title = m[1]
      title = title.strip
      self.title = title
      self.got_at = Time.now
      self.save!
    end
  end
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myapp/app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: %i[ show edit update destroy ]

  # GET /folders or /folders.json
  def index
    @folders = Folder.all
  end

  # GET /folders/1 or /folders/1.json
  def show
    @urls = Url.where(folder_id: params[:id])
  end

  # GET /folders/1/add_urls
  def add_urls
    @folder = Folder.find(params[:folder_id])

    if request.post?
      urls = params[:urls].split(/\R/)
      urls.each do |url|
        url = url.strip
        next if not url.match(/\A#{URI::regexp(%w(http https))}\z/)

        @url = Url.new(folder_id: params[:folder_id], url: url)
        @url.save
        @url.delay.acquire_title
      end

      redirect_to folder_url(@folder)
    end
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders or /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to folder_url(@folder), notice: "Folder was successfully created." }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1 or /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to folder_url(@folder), notice: "Folder was successfully updated." }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1 or /folders/1.json
  def destroy
    @folder.destroy

    respond_to do |format|
      format.html { redirect_to folders_url, notice: "Folder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def folder_params
      params.require(:folder).permit(:name, :note)
    end
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/folders_helper.rb
module FoldersHelper
end

myapp/app/views/folders/_form.html.erb
<%= form_with(model: folder) do |form| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

myapp/app/views/folders/add_urls.html.erb
<h1>Add URLs</h1>

<%= form_with do |form| %>
  <%= form.label :urls, "URLs:" %>
  <%= form.text_area :urls, size: '50x10' %>
  <br>
  <%= form.submit "Add" %>
<% end %>

<%= link_to 'Back', folders_path %>

myapp/app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

myapp/app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= folder.note %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

myapp/app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

myapp/app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<p>
  <strong>Note:</strong>
  <%= @folder.note %>
</p>

<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Title</th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url.truncate(60) %></td>
        <td><%= if url.title then url.title.truncate(80) end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add URLs', folder_add_urls_path(@folder)  %> |
<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gyotaku</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>